In [117]:
# For reading data sets from the web.
import pandas
# For lots of great things.
import numpy as np
# To make our plots.
import matplotlib.pyplot as plt
%matplotlib inline
# Because sympy and LaTeX make
# everything look wonderful!
from sympy import *
init_printing(use_latex=True)
from IPython.display import display
# We will use this to check our implementation...
from sklearn.decomposition import PCA
# We will grab another data set using Keras
# after we finish up with Iris...
import keras
# Need this for LabelEncoder
from sklearn import preprocessing

In [118]:
student_data = np.array(pandas.read_table("./student-por.csv",
delimiter=";", header=0))

In [119]:
student_data.shape

In [120]:
le = preprocessing.LabelEncoder()

# Encoding non-numeric data to integers

In [121]:
# School (binomial)
le.fit(student_data[:,0])
student_data[:,0] = le.transform(student_data[:,0])

In [122]:
# Sex (binomial)
le.fit(student_data[:,1])
student_data[:,1] = le.transform(student_data[:,1])

In [123]:
# address (binomial)
le.fit(student_data[:,3])
student_data[:,3] = le.transform(student_data[:,3])

In [124]:
# Famsize (binomial)
le.fit(student_data[:,4])
student_data[:,4] = le.transform(student_data[:,4])

In [125]:
# Pstatus (binomial)
le.fit(student_data[:,5])
student_data[:,5] = le.transform(student_data[:,5])

In [126]:
# Mjob (nominal)
le.fit(student_data[:,8])
student_data[:,8] = le.transform(student_data[:,8])

In [127]:
# Fjob (nominal)
le.fit(student_data[:,9])
student_data[:,9] = le.transform(student_data[:,9])

In [128]:
# Reason (nominal)
le.fit(student_data[:,10])
student_data[:,10] = le.transform(student_data[:,10])

In [129]:
# Guardian (nominal)
le.fit(student_data[:,11])
student_data[:,11] = le.transform(student_data[:,11])

In [130]:
# schoolsup (binomial)
le.fit(student_data[:,15])
student_data[:,15] = le.transform(student_data[:,15])

In [131]:
# famsup (binomial)
le.fit(student_data[:,16])
student_data[:,16] = le.transform(student_data[:,16])

In [132]:
# paid (binomial)
le.fit(student_data[:,17])
student_data[:,17] = le.transform(student_data[:,17])

In [133]:
# activities (binomial)
le.fit(student_data[:,18])
student_data[:,18] = le.transform(student_data[:,18])

In [134]:
# nursery (binomial)
le.fit(student_data[:,19])
student_data[:,19] = le.transform(student_data[:,19])

In [135]:
# higher (binomial)
le.fit(student_data[:,20])
student_data[:,20] = le.transform(student_data[:,20])

In [136]:
# internet (binomial)
le.fit(student_data[:,21])
student_data[:,21] = le.transform(student_data[:,21])

In [137]:
# romantic (binomial)
le.fit(student_data[:,22])
student_data[:,22] = le.transform(student_data[:,22])

In [138]:
student_data

array([[0, 0, 18, ..., 0, 11, 11],
       [0, 0, 17, ..., 9, 11, 11],
       [0, 0, 15, ..., 12, 13, 12],
       ...,
       [1, 0, 18, ..., 11, 12, 9],
       [1, 1, 17, ..., 10, 10, 10],
       [1, 1, 18, ..., 10, 11, 11]], dtype=object)

# Encoding 0's to -1 for binomial data.

### Surely there's a one line method to do this... right, Keras?

In [139]:
school = student_data[:,0]
school = np.where(school==0, -1, school)
student_data[:,0] = school

In [140]:
sex = student_data[:,1]
sex = np.where(sex==0, -1, sex)
student_data[:,1] = sex

In [141]:
address = student_data[:,3]
address = np.where(address==0, -1, address)
student_data[:,3] = address

In [142]:
famsize = student_data[:,4]
famsize = np.where(famsize==0, -1, famsize)
student_data[:,4] = famsize

In [143]:
Pstatus = student_data[:,5]
Pstatus = np.where(Pstatus==0, -1, Pstatus)
student_data[:,5] = Pstatus

In [144]:
schoolsup = student_data[:,15]
schoolsup = np.where(schoolsup==0, -1, schoolsup)
student_data[:,15] = schoolsup

In [145]:
famsup = student_data[:,16]
famsup = np.where(famsup==0, -1, famsup)
student_data[:,16] = famsup

In [146]:
paid = student_data[:,17]
paid = np.where(paid==0, -1, paid)
student_data[:,17] = paid

In [147]:
activities = student_data[:,18]
activities = np.where(activities==0, -1, activities)
student_data[:,18] = activities

In [148]:
nursery = student_data[:,19]
nursery = np.where(nursery==0, -1, nursery)
student_data[:,19] = nursery

In [149]:
higher = student_data[:,20]
higher = np.where(higher==0, -1, higher)
student_data[:,20] = higher

In [150]:
internet = student_data[:,21]
internet = np.where(internet==0, -1, internet)
student_data[:,21] = internet

In [151]:
romantic = student_data[:,22]
romantic = np.where(romantic==0, -1, romantic)
student_data[:,22] = romantic

# Standardizing the nominal and numerical data.

In [152]:
scaler = preprocessing.StandardScaler()

### I don't think this warning is THAT concerning

In [153]:
temp = student_data[:,[2,14,29,30,31]]
Standardized = scaler.fit_transform(temp)

/nfshome/apps/python-3.6.7/lib/python3.6/site-packages/sklearn/utils/validation.py:590: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/nfshome/apps/python-3.6.7/lib/python3.6/site-packages/sklearn/utils/validation.py:590: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


### Not sure about the -0.0 for the mean...

In [154]:
print('Mean:', round(Standardized.mean()))
print('Standard deviation:', Standardized.std())

Mean: 0.0
Standard deviation: 1.0


In [155]:
student_data[:,[2,14,29,30,31]] = Standardized

## 1-of-C encode nominal data

In [156]:
# Mother's job
## Teacher, Health Care, Civil Services, At Home, Other

# index of current feature
index = 8

# unique values this feature can inhibit
uniqueVals = Matrix(np.unique(student_data[:,index])).T
display(uniqueVals)

# convert numerical data into categories
shape = uniqueVals.shape[1]
categoricalArr = keras.utils.to_categorical(student_data[:,index], shape)
for i in range (649):
    student_data[i,index] = [categoricalArr[i,:]]
display(student_data[:,index].shape)
display(student_data[:5,index])

[0  1  2  3  4]

array([list([array([1., 0., 0., 0., 0.], dtype=float32)]),
       list([array([1., 0., 0., 0., 0.], dtype=float32)]),
       list([array([1., 0., 0., 0., 0.], dtype=float32)]),
       list([array([0., 1., 0., 0., 0.], dtype=float32)]),
       list([array([0., 0., 1., 0., 0.], dtype=float32)])], dtype=object)

In [157]:
# Father's Job
## Teacher, Health Care, Civil Services, At Home, Other
index = 9
uniqueVals = Matrix(np.unique(student_data[:,index])).T
shape = uniqueVals.shape[1]
categoricalArr = keras.utils.to_categorical(student_data[:,index], shape)
for i in range (649):
    student_data[i,index] = [categoricalArr[i,:]]

In [158]:
# Reason for Choosing This School
## Close to Home, School Reputation, Course Prefrence, Other
index = 10
uniqueVals = Matrix(np.unique(student_data[:,index])).T
shape = uniqueVals.shape[1]
categoricalArr = keras.utils.to_categorical(student_data[:,index], shape)
for i in range (649):
    student_data[i,index] = [categoricalArr[i,:]]

In [159]:
# Gaurdian
## Mother, Father, Other
index = 11
uniqueVals = Matrix(np.unique(student_data[:,index])).T
shape = uniqueVals.shape[1]
categoricalArr = keras.utils.to_categorical(student_data[:,index], shape)
for i in range (649):
    student_data[i,index] = [categoricalArr[i,:]]

# Thermometer Encode Nominal Data

In [160]:
# Mother's Education
## None, Primary (4th grade), 5th to 9th grade, Secondary, Higher
index = 6
display(student_data[0:5,index])

array([4, 1, 1, 4, 3], dtype=object)

In [161]:
uniqueVals = Matrix(np.unique(student_data[:,index])).T
display(uniqueVals)
shape = uniqueVals.shape[1]

[0  1  2  3  4]

In [162]:
# https://stackoverflow.com/questions/49080613/numpy-thermometer-encoding
thermArr = np.array([student_data[:,index]], dtype=np.uint8)
thermArr = np.fliplr(np.unpackbits((1 << thermArr) - 1).reshape(-1,8))
display(thermArr[0:5,:])
display(thermArr[0:5,:shape-1])

array([[1, 1, 1, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 0]], dtype=uint8)

array([[1, 1, 1, 1],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 1, 1, 1],
       [1, 1, 1, 0]], dtype=uint8)

In [163]:
for i in range (649):
    student_data[i,index] = [thermArr[i,:shape-1]]
display(student_data[0:5,index])

array([list([array([1, 1, 1, 1], dtype=uint8)]),
       list([array([1, 0, 0, 0], dtype=uint8)]),
       list([array([1, 0, 0, 0], dtype=uint8)]),
       list([array([1, 1, 1, 1], dtype=uint8)]),
       list([array([1, 1, 1, 0], dtype=uint8)])], dtype=object)

In [164]:
# Father's Education
## None, Primary (4th grade), 5th to 9th grade, Secondary, Higher
index = 7
display(student_data[0:5,index])
uniqueVals = Matrix(np.unique(student_data[:,index])).T
shape = uniqueVals.shape[1]
thermArr = np.array([student_data[:,index]], dtype=np.uint8)
thermArr = np.fliplr(np.unpackbits((1 << thermArr) - 1).reshape(-1,8))
for i in range (649):
    student_data[i,index] = [thermArr[i,:shape-1]]
display(student_data[0:5,index])

array([4, 1, 1, 2, 3], dtype=object)

array([list([array([1, 1, 1, 1], dtype=uint8)]),
       list([array([1, 0, 0, 0], dtype=uint8)]),
       list([array([1, 0, 0, 0], dtype=uint8)]),
       list([array([1, 1, 0, 0], dtype=uint8)]),
       list([array([1, 1, 1, 0], dtype=uint8)])], dtype=object)

In [165]:
# Travel Time
## <15min, 15min - 30min, 30min - 1hour, >1hour
index = 12
uniqueVals = Matrix(np.unique(student_data[:,index])).T
shape = uniqueVals.shape[1]
thermArr = np.array([student_data[:,index]], dtype=np.uint8)
thermArr = np.fliplr(np.unpackbits((1 << thermArr) - 1).reshape(-1,8))
for i in range (649):
    student_data[i,index] = [thermArr[i,:shape-1]]
    
# Study Time
## <2hours, 2hours - 5hours, 5hours - 10hours, >10hours
index = 13
uniqueVals = Matrix(np.unique(student_data[:,index])).T
shape = uniqueVals.shape[1]
thermArr = np.array([student_data[:,index]], dtype=np.uint8)
thermArr = np.fliplr(np.unpackbits((1 << thermArr) - 1).reshape(-1,8))
for i in range (649):
    student_data[i,index] = [thermArr[i,:shape-1]]
    
# Failures
## 0, 1, 2, 3, 4+
index = 14
uniqueVals = Matrix(np.unique(student_data[:,index])).T
shape = uniqueVals.shape[1]
thermArr = np.array([student_data[:,index]], dtype=np.uint8)
thermArr = np.fliplr(np.unpackbits((1 << thermArr) - 1).reshape(-1,8))
for i in range (649):
    student_data[i,index] = [thermArr[i,:shape-1]]
    
# Free Time
## 1 - very low to 5 - very high
index = 24
uniqueVals = Matrix(np.unique(student_data[:,index])).T
shape = uniqueVals.shape[1]
thermArr = np.array([student_data[:,index]], dtype=np.uint8)
thermArr = np.fliplr(np.unpackbits((1 << thermArr) - 1).reshape(-1,8))
for i in range (649):
    student_data[i,index] = [thermArr[i,:shape-1]]
    
# Going Out With Friends
## 1 - very low to 5 - very high
index = 25
uniqueVals = Matrix(np.unique(student_data[:,index])).T
shape = uniqueVals.shape[1]
thermArr = np.array([student_data[:,index]], dtype=np.uint8)
thermArr = np.fliplr(np.unpackbits((1 << thermArr) - 1).reshape(-1,8))
for i in range (649):
    student_data[i,index] = [thermArr[i,:shape-1]]
    
# Weekend Alcohol Consumption
## 1 - very low to 5 - very high
index = 26
uniqueVals = Matrix(np.unique(student_data[:,index])).T
shape = uniqueVals.shape[1]
thermArr = np.array([student_data[:,index]], dtype=np.uint8)
thermArr = np.fliplr(np.unpackbits((1 << thermArr) - 1).reshape(-1,8))
for i in range (649):
    student_data[i,index] = [thermArr[i,:shape-1]]
    
# Workday Alcohol Consumption
## 1 - very low to 5 - very high
index = 27
uniqueVals = Matrix(np.unique(student_data[:,index])).T
shape = uniqueVals.shape[1]
thermArr = np.array([student_data[:,index]], dtype=np.uint8)
thermArr = np.fliplr(np.unpackbits((1 << thermArr) - 1).reshape(-1,8))
for i in range (649):
    student_data[i,index] = [thermArr[i,:shape-1]]
    
# Current Health Status
## 1 - very low to 5 - very high
index = 28
uniqueVals = Matrix(np.unique(student_data[:,index])).T
shape = uniqueVals.shape[1]
thermArr = np.array([student_data[:,index]], dtype=np.uint8)
thermArr = np.fliplr(np.unpackbits((1 << thermArr) - 1).reshape(-1,8))
for i in range (649):
    student_data[i,index] = [thermArr[i,:shape-1]]

### Convert results to one-hot encoding
#### the actual output vector doesn't include at least one example of each possible grade so I made a vector of all possibilities for to_categorical

In [166]:
possible_results = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]

## Getting a weird error in the training below
## am I storing the data wrong here?

In [249]:
results = student_data[:,32]
y = keras.utils.to_categorical(results, len(possible_results))
x = student_data[:,:32]


# Data is now preprocessed

In [250]:
model = keras.Sequential()

In [251]:
input_size = x.shape[1]
output_size = y.shape[1]

In [252]:
# create the hidden layer
model.add(keras.layers.Dense(400,input_dim=input_size,activation='relu'))

In [253]:
model.add(keras.layers.Dense(200,activation='relu'))

In [254]:
# output layer
model.add(keras.layers.Dense(output_size,activation='softmax'))

In [255]:
# compile
model.compile(loss='categorical_crossentropy',optimizer='adam', metrics=['accuracy'])

In [256]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_14 (Dense)             (None, 400)               13200     
_________________________________________________________________
dense_15 (Dense)             (None, 200)               80200     
_________________________________________________________________
dense_16 (Dense)             (None, 20)                4020      
Total params: 97,420
Trainable params: 97,420
Non-trainable params: 0
_________________________________________________________________


# Model Training


In [257]:
history = model.fit(x,y,batch_size = 32, epochs = 160, verbose = 0, validation_split = 0.25)

ValueError: setting an array element with a sequence.

In [ ]:
#plt.plot(history.history['loss'])
#plt.title('model loss')
#plt.ylabel('loss')
#plt.xlabel('epoch')
#plt.legend(['train'], loc='upper left')
#plt.show()


In [ ]:
score = model.evaluate(x,y, verbose=0)

In [ ]:
plt.figure(1)

# summarize history for accuracy

plt.subplot(211)
plt.plot(history.history['acc'])
plt.plot(history.history['val_acc'])
plt.title('model accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['train','test'], loc ='upper left')

# summarize history for loss

plt.subplot(212)
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train','test'], loc ='upper left')

plt.tight_layout()
plt.show()

In [258]:
print('Test loss:', score[0])
print('Test accuracy:', score[1])

NameError: name 'score' is not defined

In [259]:
## PCAs of Data

In [260]:
#def func(X):
 #   return X
#xFunc = np.apply_along_axis(func,0,x)


#U,S,V = np.linalg.svd(xFunc,full_matrices=True)

# Plot the percent of variance accounted for by each feature
#plt.plot(100.0*S/np.sum(S))
#plt.ylabel("Percent Variance")
#plt.xlabel("Singular Value")
#plt.show()

In [261]:
# https://www.youtube.com/watch?v=Lsue2gEM9D0
pca=PCA()
pca.fit(x)
pca_data = pca.transform(x)

ValueError: setting an array element with a sequence.

In [262]:
per_var = np.round(pca.explained_variance_ratio_* 100, decimals = 1)
labels = [str(i) for i in range (1, len(per_var)+1)]

plt.bar(x=range(1,len(per_var)+1), height=per_var, tick_label=labels)
plt.ylabel("% var")
plt.xlabel("PC")
plt.title("Scree Plot")
plt.show()

AttributeError: 'PCA' object has no attribute 'explained_variance_ratio_'